### ISSUE TITLE
What's the plan here?

### ISSUE THREAD

**Issue by howardroark** [plugbunch/PlugBunch#1]
I'm curious!

**Comment by DILEEP-YADAV** [comment]
@howardroark   ,  We are planing to provide single cordova plugin to multiple Devices

**Comment by DILEEP-YADAV** [comment]
single technologies , single plugin , multiple devices

**Comment by howardroark** [comment]
Ahhh OK ... Plug + Bunch ;). So would you say that adds up to IOS + Android + Windows 10 + BlackBerry 10?

**Comment by DILEEP-YADAV** [comment]
@howardroark       We will try level best
