### ISSUE TITLE
Plans to bring NFC support to IOS.

### ISSUE THREAD

**Issue by howardroark** [plugbunch/PlugBunch#2]
I think one of the biggest things the world of Cordova lacks it NFC support for IOS.  Is this something that you may be working towards?

Thanks!

**Comment by DILEEP-YADAV** [comment]
NFC connection is made through magnetic coupling, creating the electronic field between the devices themselves, only when both devices are very close and your mfc apps are turn on/ready. bluetooth signals are their own small broadcasting antennae and it is therfore more code admin to create small network firewindows & firewalls (whitelists or blacklists) (pairing) based on IPv6 or even more of headache, ipv4.

Android API have build in support for the same . but iOS API not for public use.

**Comment by howardroark** [comment]
Ahhh... yeah I see it is not open to developers... http://stackoverflow.com/questions/25753473/reading-nfc-tags-with-iphone-6-ios-8

I guess Apple is always thinking about corporate strategy first.  They likely figure that if they allow developers to build their own payment solutions using the NFC then they are opening up potential competition.  I'm sure their long term goal is to dominate the "payment market".

**Comment by DILEEP-YADAV** [comment]
@howardroark  sure!
